name: Zecur Build Application

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install

      - name: Build VSIX Package
        # Kita gunakan npx agar tidak perlu install global
        run: npx vsce package --no-dependencies -y

      - name: Upload VSIX Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Zecur-Extension
          path: "*.vsix"
